### ISSUE TITLE
Vagrant 1.8.7 embedded libcurl provides out-of-date version

### ISSUE THREAD

**Issue by WaPoNe** [gmdotnet/Vagrant-LEMP-Magento#1]
After package installation on OS X, trying to run `vagant up` command, you receive this error:

```
The box 'giuseppemorelli/lemp-magento-stack' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/giuseppemorelli/lemp-magento-stack"]
Error: 
```

The issue is due to _libcurl_ of Vagrant in version 1.8.7
To fix it, you have to link /opt/vagrant/embedded/bin/curl to OS X's curl binary:`ln -s /usr/bin/curl /opt/vagrant/embedded/bin/curl`.

**Comment by giuseppemorelli** [comment]
Thanks @WaPoNe!

Just added the solution on wiki pages:  https://github.com/gmdotnet/Vagrant-LEMP-Magento/wiki/faq
